---
# file: roles/hardening/tasks/hardening_debian.yml

- name: Install recommended security packages
  action: apt pkg={{ item }} state=latest
  with_items:
    - fail2ban
    - logwatch
    - unattended-upgrades
    - chkrootkit
    - lynis

- name: Set up an account
  user: home=/home/{{ hardening_user.id }} name={{ hardening_user.id }} groups=sudo,adm password={{ hardening_user.password }} shell={{ hardening_user.shell }} state=present
  when: hardening_user.id is defined

- name: Add RSA key to the remote host
  authorized_key: user='{{ hardening_user.id }}' key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: hardening_user.id is defined

- name: Make logwatch mail weekly
  lineinfile: dest=/etc/cron.weekly/00logwatch regexp="^/usr/sbin/logwatch" line="/usr/sbin/logwatch --output mail --mailto {{ hardening_admin_email }} --detail high" state=present create=yes

- name: Enable automatic security updates
  apt: pkg=unattended-upgrades
       state=latest
       update_cache=yes
       cache_valid_time=7200

- name: Configure automatic security update
  template: dest=/etc/apt/apt.conf.d/50unattended-upgrades
            src=unattended-upgrades.j2
            mode=0640
            group=adm
            backup=yes

- name: Configure automatic updates settings
  template: dest=/etc/apt/apt.conf.d/02periodic
            src=apt-periodic.j2
            mode=0640
            group=adm
            backup=yes

- name: Make OpenSSH secure(r)
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp='^#?{{ item.key }}'
    line='{{ item.key }} {{ item.value }}'
  with_items:
    - { key: 'PermitRootLogin', value: 'no'}
    - { key: 'PasswordAuthentication', value: 'no'}
    - { key: 'X11Forwarding', value: 'no'}
  notify: restart ssh

- name: OpenSSH allow only very strong crypto
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp='^#?{{ item.key }}'
    line='{{ item.key }} {{ item.value }}'
  with_items:
    - { key: 'Ciphers', value: 'aes256-ctr'}
    - { key: 'MACs', value: 'hmac-sha2-512'}
  notify: restart ssh
  when: ssh_strong_ciphers
