---
# file: roles/hardening/tasks/hardening_debian.yml
# TODO: http://www.newnettechnologies.com/linux-server-hardening.html
- name: Install recommended security packages
  apt: pkg={{ item }} state=latest
  with_items:
    - acct
    - aide
    - apt-show-versions
    - auditd
    - binutils
    - chkrootkit
    - clamav
    - clamav-daemon
    - debsums
    - fail2ban
    - iptables-persistent
    - libdate-manip-perl
    - libpam-cracklib
    - libreadline5
    - libruby
    - mailutils
    - ruby
    - ssl-cert
    - sysstat
    - unattended-upgrades
    - unhide.rb

- name: Enable automatic security updates
  apt: pkg=unattended-upgrades
       state=latest
       update_cache=yes
       cache_valid_time=7200

- name: Configure automatic security update
  template: dest=/etc/apt/apt.conf.d/50unattended-upgrades
            src=unattended-upgrades.j2
            mode=0640
            group=adm
            backup=yes

- name: Configure automatic updates settings
  template: dest=/etc/apt/apt.conf.d/02periodic
            src=apt-periodic.j2
            mode=0640
            group=adm
            backup=yes

- name: Configure fail2ban
  template: dest=/etc/fail2ban/jail.local
            src=jail.local.j2
            mode=0640
            group=adm
            backup=yes
  notify: restart fail2ban

- include: logwatch.yml
  when: install_logwatch == 'true'

- name: Get RKHunter
  get_url: url=http://downloads.sourceforge.net/project/rkhunter/rkhunter/1.4.2/rkhunter-1.4.2.tar.gz dest=/usr/local/src/rkhunter-1.4.2.tar.gz

- name: extract RKHunter
  unarchive: src=/usr/local/src/rkhunter-1.4.2.tar.gz dest=/usr/local/src copy=no

- name: install RKHunter
  shell: ./installer.sh --layout /usr --install
  args:
    chdir: /usr/local/src/rkhunter-1.4.2

- name: Get lynis 2.1.1
  get_url: url=https://cisofy.com/files/lynis-2.1.1.tar.gz dest=/usr/local/src

- name: Extract lynis
  unarchive: src=/usr/local/src/lynis-2.1.1.tar.gz dest=/usr/local/src copy=no

- name: Change default UMASK in /etc/login.defs
  lineinfile:
    dest=/etc/login.defs
    state=present
    regexp='^#?{{ item.key }}'
    line='{{ item.key }} {{ item.value }}'
  with_items:
    - { key: 'UMASK', value: '027'}

- name: Change default umask in /etc/init.d/rc
  lineinfile:
    dest=/etc/init.d/rc
    state=present
    regexp='^#?{{ item.key }}'
    line='{{ item.key }} {{ item.value }}'
  with_items:
    - { key: 'umask', value: '027'}

- name: Adjust kernel options
  sysctl:
    state=present
    name={{ item.key }}
    value={{ item.value }}
  with_items:
    - { key: 'net.ipv4.icmp_echo_ignore_broadcasts', value: '1'}
    - { key: 'net.ipv4.conf.all.accept_source_route', value: '0'}
    - { key: 'net.ipv4.conf.default.accept_source_route', value: '0'}
    - { key: 'net.ipv6.conf.default.accept_source_route', value: '0'}
    - { key: 'net.ipv4.conf.all.send_redirects', value: '0'}
    - { key: 'net.ipv4.conf.default.send_redirects', value: '0'}
    - { key: 'net.ipv4.tcp_max_syn_backlog', value: '2048'}
    - { key: 'net.ipv4.tcp_synack_retries', value: '2'}
    - { key: 'net.ipv4.tcp_syn_retries', value: '5'}
    - { key: 'net.ipv4.conf.all.log_martians', value: '1'}
    - { key: 'net.ipv4.icmp_ignore_bogus_error_responses', value: '1'}
    - { key: 'net.ipv4.conf.all.accept_redirects', value: '0'}
    - { key: 'net.ipv6.conf.all.accept_redirects', value: '0'}
    - { key: 'net.ipv4.conf.default.accept_redirects', value: '0'}
    - { key: 'net.ipv6.conf.default.accept_redirects', value: '0'}
    - { key: 'net.ipv4.icmp_echo_ignore_all', value: '1'}
  notify: reload sysctl.conf

- name: Make OpenSSH secure(r)
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp='^#?{{ item.key }}'
    line='{{ item.key }} {{ item.value }}'
  with_items:
    - { key: 'Port', value: '{{ssh_port}}'}
    - { key: 'PermitRootLogin', value: 'no'}
    - { key: 'PasswordAuthentication', value: 'no'}
    - { key: 'PubkeyAuthentication', value: 'yes'}
    - { key: 'ChallengeResponseAuthentication', value: 'no'}
    - { key: 'X11Forwarding', value: 'no'}

- name: OpenSSH allow only very strong crypto
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp='^#?{{ item.key }}'
    line='{{ item.key }} {{ item.value }}'
  with_items:
    - { key: 'Ciphers', value: 'aes256-ctr,aes192-ctr,aes128-ctr'}
    - { key: 'MACs', value: 'hmac-sha2-512,hmac-sha2-256,hmac-ripemd160'}
    - { key: 'KexAlgorithms', value: 'diffie-hellman-group-exchange-sha256'}
  when: ssh_strong_ciphers
  notify: restart ssh

- name: Finish hardening and restart ssh
  service: name=ssh state=restarted
