---
# file: roles/hardening/tasks/hardening_debian.yml
- name: Install recommended security packages
  apt: pkg={{ item }} state=latest
  with_items:
    - fail2ban
    - aide
    - logwatch
    - unattended-upgrades
    - chkrootkit
    - libpam-cracklib
    - apt-show-versions
    - auditd
    - clamav
    - clamav-daemon
    - binutils
    - libreadline5
    - libruby
    - ruby
    - ssl-cert
    - unhide.rb
    - mailutils
    - iptables-persistent
    - libdate-manip-perl

- name: Enable automatic security updates
  apt: pkg=unattended-upgrades
       state=latest
       update_cache=yes
       cache_valid_time=7200

- name: Configure automatic security update
  template: dest=/etc/apt/apt.conf.d/50unattended-upgrades
            src=unattended-upgrades.j2
            mode=0640
            group=adm
            backup=yes

- name: Configure automatic updates settings
  template: dest=/etc/apt/apt.conf.d/02periodic
            src=apt-periodic.j2
            mode=0640
            group=adm
            backup=yes

- name: Configure fail2ban
  template: dest=/etc/fail2ban/jail.local
            src=jail.local.j2
            mode=0640
            group=adm
            backup=yes
  notify: restart fail2ban

- name: Configure logwatch
  template: dest=/etc/logwatch/conf/logwatch.conf
            src=logwatch.conf.j2
            mode=0640
            group=adm
            backup=yes

- name: Get RKHunter
  get_url: url=http://downloads.sourceforge.net/project/rkhunter/rkhunter/1.4.2/rkhunter-1.4.2.tar.gz dest=/usr/local/src/rkhunter-1.4.2.tar.gz

- name: extract RKHunter
  unarchive: src=/usr/local/src/rkhunter-1.4.2.tar.gz dest=/usr/local/src copy=no

- name: install RKHunter
  shell: ./installer.sh --layout /usr --install
  args:
    chdir: /usr/local/src/rkhunter-1.4.2

- name: Get lynis 2.1.1
  get_url: url=https://cisofy.com/files/lynis-2.1.1.tar.gz dest=/usr/local/src

- name: Extract lynis
  unarchive: src=/usr/local/src/lynis-2.1.1.tar.gz dest=/usr/local/src copy=no

- name: Make OpenSSH secure(r)
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp='^#?{{ item.key }}'
    line='{{ item.key }} {{ item.value }}'
  with_items:
    - { key: 'Port', value: '{{ssh_port}}'}
    - { key: 'PermitRootLogin', value: 'no'}
    - { key: 'PasswordAuthentication', value: 'no'}
    - { key: 'X11Forwarding', value: 'no'}

- name: OpenSSH allow only very strong crypto
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp='^#?{{ item.key }}'
    line='{{ item.key }} {{ item.value }}'
  with_items:
    - { key: 'Ciphers', value: 'aes256-ctr'}
    - { key: 'MACs', value: 'hmac-sha2-512,hmac-md5'}
  when: ssh_strong_ciphers

- name: Finish hardening and restart ssh
  service: name=ssh state=restarted
